### ISSUE TITLE
Strona główna

### ISSUE THREAD

**Issue by Wariatingo** [ZSET-Leszno/nk-metamorfoza#8]
Do zrobienia no nie

**Comment by medukin** [comment]
akceptacja cookies 👍

**Comment by mewash999** [comment]
telefon:
- navbar nie pokazuje sie
- ceny przesuwaja sie
- ostatni rekord chowa sie
- nie pokazuje sie wszystkie obrazki (4 z 8)

**Comment by mewash999** [comment]
navbar nie pokazuje sie (telefon)
odnosniki w nav
stopka

**Comment by mewash999** [comment]
finito 👍
